name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # This workflow uses an API token stored in the PYPI_API_TOKEN secret

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history and tags for setuptools_scm

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: python -m pip install --upgrade pip build twine

    - name: Build package
      # setuptools_scm will automatically determine the version from the Git tag
      run: python -m build

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        # API token stored in GitHub Secrets
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}